"use client";
import { useEffect, useState } from "react";
import { formatDateDMY } from "@/app/lib/displayFormat";
const LABEL={earned:"Earned Leave","comp-off":"Compensatory-Off",unpaid:"Unpaid Leave",paternity:"Paternity Leave (legacy)"};
export default function EmployeeLeavePage(){
 const [balance,setBalance]=useState(null),[requests,setRequests]=useState([]),[form,setForm]=useState({fromDate:"",toDate:"",leaveType:"earned",leaveFraction:1,halfDayPart:"first-half",note:""}),[msg,setMsg]=useState("");
 const load=()=>Promise.all([fetch("/api/leave-balance").then(r=>r.json()),fetch("/api/leave-requests").then(r=>r.json())]).then(([b,q])=>{setBalance(b.balance);setRequests(q.requests||[])});
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setMsg("");const r=await fetch("/api/leave-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,leaveFraction:Number(form.leaveFraction)})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||"Request submit nahi hui");return}setMsg("Leave request submitted.");setForm({...form,fromDate:"",toDate:"",note:""});load();}
 return <div className="p-3 sm:p-6 lg:p-8 space-y-6"><div><p className="text-xs uppercase text-slate-400">Leave</p><h1 className="text-xl font-semibold">Apply / View Leave</h1></div>
 <div className="grid sm:grid-cols-2 gap-3"><Card t="Earned Leave" v={balance?.earned?.available}/><Card t="Compensatory-Off" v={balance?.compOff?.available}/></div>
 <form onSubmit={submit} className="bg-white border rounded-2xl p-5 space-y-4"><h2 className="font-semibold">Request Leave</h2>{msg&&<p className="text-sm text-indigo-700">{msg}</p>}
 <div className="grid sm:grid-cols-2 gap-3"><Field label="From"><input required type="date" value={form.fromDate} onChange={e=>setForm({...form,fromDate:e.target.value})} className="input"/></Field><Field label="To"><input required type="date" value={form.toDate} onChange={e=>setForm({...form,toDate:e.target.value})} className="input"/></Field></div>
 <div className="grid sm:grid-cols-2 gap-3"><Field label="Leave Type"><select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})} className="input"><option value="earned">Earned Leave</option><option value="comp-off">Compensatory-Off</option><option value="unpaid">Unpaid Leave</option></select></Field><Field label="Duration"><select value={form.leaveFraction} onChange={e=>setForm({...form,leaveFraction:Number(e.target.value)})} className="input"><option value={1}>Full Day</option><option value={0.5}>Half Day</option></select></Field></div>
 {Number(form.leaveFraction)===0.5&&<Field label="Half"><select value={form.halfDayPart} onChange={e=>setForm({...form,halfDayPart:e.target.value})} className="input"><option value="first-half">First Half</option><option value="second-half">Second Half</option></select></Field>}
 <Field label="Note"><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className="input" rows={2}/></Field><button className="px-4 py-2 rounded-lg bg-indigo-600 text-white text-sm">Submit Request</button></form>
 <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Type</th><th className="p-3 text-left">Dates</th><th className="p-3">Duration</th><th className="p-3">Status</th></tr></thead><tbody>{requests.map(r=><tr key={r._id} className="border-t"><td className="p-3">{LABEL[r.leaveType]||r.leaveType}</td><td className="p-3">{formatDateDMY(r.fromDate)} → {formatDateDMY(r.toDate)}</td><td className="p-3 text-center">{Number(r.leaveFraction||1)===0.5?`Half Day (${r.halfDayPart==="first-half"?"First":"Second"} Half)`:"Full Day"}</td><td className="p-3 text-center capitalize">{r.status}</td></tr>)}</tbody></table></div></div>;
}
function Card({t,v}){return <div className="bg-white border rounded-xl p-4"><p className="text-xs text-slate-500">{t}</p><p className="text-2xl font-semibold">{v??"-"} days</p></div>}
function Field({label,children}){return <label className="block text-sm text-slate-700"><span className="block mb-1">{label}</span>{children}<style jsx>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.65rem;padding:.55rem .7rem;background:white}`}</style></label>}
