"use client";
import { use, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
const DEPARTMENTS=["Automation","Sales","Electrical","HR"]; const DESIGNATIONS=["Manager","Assistant Manager","Executive","Junior","Trainee"];
export default function EditEmployeePage({params}){ const {id}=use(params); const router=useRouter(); const [form,setForm]=useState(null),[heads,setHeads]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([fetch(`/api/employees/${id}`).then(r=>r.json()),fetch('/api/users').then(r=>r.json())]).then(([a,u])=>{setForm(a.employee||null);setHeads((u.users||[]).filter(x=>x.role==='hr'&&x.isActive!==false));}).catch(()=>setError('Employee load nahi ho paya'));},[id]);
 const update=(k,v)=>setForm(f=>({...f,[k]:v})); const gross=useMemo(()=>form?['basicSalary','hra','otherAllowance'].reduce((t,k)=>t+(Number(form[k])||0),0):0,[form]);
 async function save(e){e.preventDefault();setSaving(true);setError('');const payload={...form, reportingHead: typeof form.reportingHead==='object' ? form.reportingHead?._id : form.reportingHead}; if(form.wageType==='monthly') payload.salary=gross; const r=await fetch(`/api/employees/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(d.error||'Update failed');return;}router.push('/hr/employees/all');}
 if(!form)return <div className="p-6 text-sm">{error||'Loading...'}</div>; const money=(k,l)=><div><label className="text-sm font-medium">{l}</label><input type="number" min="0" step="0.01" value={form[k]??''} onChange={e=>update(k,e.target.value)} className="w-full rounded-xl border px-3 py-2 text-sm" /></div>;
 return <div className="py-8 px-4"><form onSubmit={save} className="max-w-2xl mx-auto bg-white border rounded-2xl shadow-lg p-6 sm:p-8 space-y-4"><h1 className="text-xl font-semibold">Edit Employee</h1>{error&&<div className="text-red-700 bg-red-50 border rounded-lg p-2 text-sm">{error}</div>}
 <div><label className="text-sm font-medium">Employee ID</label><input disabled value={form.employeeId||''} className="w-full rounded-xl border bg-slate-100 px-3 py-2 text-sm" /></div>
 <div className="grid sm:grid-cols-[130px_1fr] gap-3"><select value={form.title||''} onChange={e=>update('title',e.target.value)} className="rounded-xl border px-3 py-2"><option value="">Title</option><option value="mr">Mr.</option><option value="mrs">Mrs.</option><option value="miss">Miss</option></select><input required value={form.fullName||''} onChange={e=>update('fullName',e.target.value)} className="rounded-xl border px-3 py-2" /></div>
 <div className="grid sm:grid-cols-2 gap-4"><Input l="Email" type="email" v={form.email} set={v=>update('email',v)}/><Phone l="Mobile Number" v={form.phone} set={v=>update('phone',v)}/><Phone l="Emergency Contact" v={form.emergencyContact} set={v=>update('emergencyContact',v)}/><Input l="Date of Joining" type="date" v={(form.dateOfJoining||'').slice(0,10)} set={v=>update('dateOfJoining',v)}/></div>
 <div className="grid sm:grid-cols-2 gap-4"><Select l="Department" v={form.department} set={v=>update('department',v)} items={DEPARTMENTS}/><Select l="Designation" v={form.designation} set={v=>update('designation',v)} items={DESIGNATIONS}/></div>
 <div><label className="text-sm font-medium">Reporting Head (HR)</label><select required value={typeof form.reportingHead==='object'?form.reportingHead?._id||'':form.reportingHead||''} onChange={e=>update('reportingHead',e.target.value)} className="w-full rounded-xl border px-3 py-2"><option value="">Select Reporting Head</option>{heads.map(h=><option key={h._id} value={h._id}>{h.employee?.fullName?`${h.employee.fullName} (${h.email})`:h.email}</option>)}</select></div>
 <div className="grid sm:grid-cols-2 gap-4"><Select l="Wage Type" v={form.wageType} set={v=>update('wageType',v)} items={[['monthly','Monthly Salary'],['daily','Daily Wage']]}/><Select l="Gender" v={form.gender||''} set={v=>update('gender',v)} items={[['male','Male'],['female','Female'],['other','Other']]}/></div>
 {form.wageType==='monthly'?<><div className="grid sm:grid-cols-3 gap-4">{money('basicSalary','Basic Salary (₹)')}{money('hra','HRA (₹)')}{money('otherAllowance','Other Allowance (₹)')}</div><div className="bg-slate-50 border rounded-xl p-3 text-sm">Monthly Gross Salary: <b>₹{gross.toFixed(2)}</b></div></>:money('salary','Per-day Rate (₹)')}
 <Input l="Blood Group" v={form.bloodGroup} set={v=>update('bloodGroup',v)}/><Input l="Address" v={form.address} set={v=>update('address',v)}/><Input l="Date of Leaving" type="date" v={(form.dateOfLeaving||'').slice(0,10)} set={v=>update('dateOfLeaving',v)}/>
 <button disabled={saving} className="w-full bg-slate-900 text-white rounded-xl py-2.5">{saving?'Saving...':'Save Changes'}</button></form></div> }
function Input({l,v,set,type='text'}){return <div><label className="text-sm font-medium">{l}</label><input type={type} value={v||''} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2 text-sm" /></div>};
function Phone({l,v,set}){return <div><label className="text-sm font-medium">{l}</label><div className="flex border rounded-xl overflow-hidden"><span className="px-3 py-2 bg-slate-50 border-r">+91</span><input required inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10} value={v||''} onChange={e=>set(e.target.value.replace(/\D/g,'').slice(0,10))} className="min-w-0 flex-1 px-3 py-2" /></div></div>};
function Select({l,v,set,items}){return <div><label className="text-sm font-medium">{l}</label><select required value={v||''} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2"><option value="">Select</option>{items.map(x=>Array.isArray(x)?<option key={x[0]} value={x[0]}>{x[1]}</option>:<option key={x} value={x}>{x}</option>)}</select></div>}
