"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function HRDashboard(){
 const [s,setS]=useState(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/dashboard-summary").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");return d}).then(setS).catch(e=>setError(e.message));},[]);
 return <div className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
  <div className="rounded-3xl bg-gradient-to-r from-slate-950 via-indigo-950 to-violet-900 text-white p-6 sm:p-8 shadow-xl"><p className="text-xs uppercase tracking-[0.22em] text-indigo-200 font-semibold">HR Control Center</p><div className="mt-2 flex items-end justify-between gap-4 flex-wrap"><div><h1 className="text-2xl sm:text-3xl font-bold">Today&apos;s Workforce Overview</h1><p className="text-sm text-slate-300 mt-2">Attendance, leave, employee records and approvals — all HR actions stay inside the HR portal.</p></div><Link href="/hr/employees/new" className="rounded-xl bg-white text-slate-900 px-4 py-2.5 text-sm font-bold shadow">+ Add Employee</Link></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Active Employees" value={s?.totalEmployees} note="Current workforce"/><Stat label="Checked In Today" value={s?.presentCount} note="Attendance activity"/><Stat label="Not Checked In" value={s?.notCheckedIn?.length} note="Needs attention"/><Stat label="On Leave Today" value={s?.onLeaveToday?.length} note="Approved leave"/></div>
  {(s?.isHolidayToday||s?.isWeekOffToday)&&<div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-800 font-medium">{s.isHolidayToday?`Today is a company holiday${s.holidayName?`: ${s.holidayName}`:""}.`:"Today is Sunday weekly off."}</div>}
  <div className="grid lg:grid-cols-3 gap-5">
   <section className="lg:col-span-2 bg-white/90 border border-white rounded-2xl shadow-sm p-5"><div className="flex justify-between items-center mb-4"><div><h2 className="font-bold text-slate-900">HR Quick Actions</h2><p className="text-xs text-slate-500 mt-1">Administrative pages only — no employee portal shortcuts.</p></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3"><Quick href="/hr/attendance" title="Mark Attendance" text="Manage daily attendance"/><Quick href="/hr/leave-requests" title="Leave Approvals" text="Review employee leave"/><Quick href="/hr/miss-punch-requests" title="Miss Punch" text="Review punch corrections"/><Quick href="/hr/overtime" title="OT / C-Off" text="Manage settlements"/><Quick href="/hr/salaries" title="Payroll" text="Salary and payroll"/><Quick href="/hr/employees/all" title="Employee Master" text="View and edit employees"/></div></section>
   <section className="bg-white/90 border border-white rounded-2xl shadow-sm p-5"><h2 className="font-bold text-slate-900">Attention Required</h2><p className="text-xs text-slate-500 mt-1 mb-4">Employees not checked in today</p>{!s?<p className="text-sm text-slate-400">Loading...</p>:s.notCheckedIn?.length?<div className="space-y-2 max-h-64 overflow-auto">{s.notCheckedIn.slice(0,10).map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="w-9 h-9 rounded-full bg-rose-100 text-rose-700 flex items-center justify-center text-xs font-bold">{x.name.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><p className="text-sm font-medium text-slate-800 truncate">{x.name}</p></div>)}</div>:<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">No pending check-in.</p>}</section>
  </div>
  <section className="bg-white/90 border border-white rounded-2xl shadow-sm p-5"><h2 className="font-bold text-slate-900">On Leave Today</h2><div className="mt-3 flex flex-wrap gap-2">{!s?<span className="text-sm text-slate-400">Loading...</span>:s.onLeaveToday?.length?s.onLeaveToday.map(x=><span key={x.id} className="rounded-full bg-amber-50 border border-amber-100 px-3 py-1.5 text-sm text-amber-800">{x.name}</span>):<span className="text-sm text-slate-500">No employee is on leave today.</span>}</div></section>
 </div>
}
function Stat({label,value,note}){return <div className="bg-white/90 border border-white rounded-2xl shadow-sm p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="text-3xl font-bold text-slate-900 mt-2">{value??"—"}</p><p className="text-xs text-slate-500 mt-1">{note}</p></div>}
function Quick({href,title,text}){return <Link href={href} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4 hover:bg-indigo-50 hover:border-indigo-100 transition"><p className="font-semibold text-slate-900">{title}</p><p className="text-xs text-slate-500 mt-1">{text}</p></Link>}
