"use client";
import { useEffect,useState } from "react";
import { formatDateDMY } from "@/app/lib/displayFormat";
const LABEL={earned:"Earned Leave","comp-off":"Compensatory-Off",unpaid:"Unpaid Leave",paternity:"Paternity Leave (legacy)"};
export default function LeaveRequestsPage(){const [requests,setRequests]=useState([]),[filter,setFilter]=useState("pending"),[busy,setBusy]=useState(null),[error,setError]=useState("");
 const load=()=>fetch(`/api/leave-requests${filter==="all"?"":`?status=${filter}`}`,{cache:"no-store"}).then(r=>r.json()).then(d=>setRequests(d.requests||[])); useEffect(()=>{load()},[filter]);
 async function review(r,status){setBusy(r._id);setError("");const x=await fetch(`/api/leave-requests/${r._id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const d=await x.json().catch(()=>({}));setBusy(null);if(!x.ok){setError(d.error||"Update failed");return}load();}
 return <div className="p-3 sm:p-6 lg:p-8 space-y-5"><div className="flex flex-wrap gap-3 justify-between"><h1 className="text-xl font-semibold">Leave Requests</h1><div className="flex gap-3"><a href="/hr/miss-punch-requests" className="text-sm underline">Miss Punch Requests</a><select value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-lg px-3 py-1 text-sm"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All</option></select></div></div>{error&&<p className="text-sm text-red-600">{error}</p>}
 <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Employee</th><th className="p-3 text-left">Type</th><th className="p-3">Dates</th><th className="p-3">Duration</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{requests.map(r=><tr key={r._id} className="border-t"><td className="p-3"><b>{r.employee?.fullName}</b><div className="text-xs text-slate-400">{r.employee?.employeeId}</div></td><td className="p-3">{LABEL[r.leaveType]||r.leaveType}</td><td className="p-3 text-center">{formatDateDMY(r.fromDate)} → {formatDateDMY(r.toDate)}</td><td className="p-3 text-center">{Number(r.leaveFraction||1)===0.5?`Half (${r.halfDayPart==="first-half"?"1st":"2nd"})`:"Full"}</td><td className="p-3 text-center capitalize">{r.status}</td><td className="p-3 text-center">{r.status==="pending"&&<div className="flex justify-center gap-2"><button disabled={busy===r._id} onClick={()=>review(r,"approved")} className="text-emerald-700">Approve</button><button disabled={busy===r._id} onClick={()=>review(r,"rejected")} className="text-red-600">Reject</button></div>}</td></tr>)}{requests.length===0&&<tr><td colSpan="6" className="p-6 text-center text-slate-400">No requests</td></tr>}</tbody></table></div></div>}
